POST http://localhost:3001/api/blogs 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inl1QGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE2NTgwMDYzMjl9.y76RA-_I7u2bFDNMxSuDUk01aJQ2xFXHQYLYZQf0SvQ

# {
#   "title": "First blogpost",
#   "author": "John Lennon",
#   "url": "www"
# }

# {
#   "title": "Fifth blogpost",
#   "author": "John Lennon",
#   "url": "www",
#   "year" : 2020
# }

{
  "title": "Eleventh blogpost",
  "author": "John Lennonr",
  "url": "www",
  "year" : 2021
}